# Generated by Django 4.1.4 on 2023-08-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_Admin', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ajouter',
            fields=[
                ('id_ajout', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_Patient', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliche',
            fields=[
                ('id_Cliche', models.AutoField(primary_key=True, serialize=False)),
                ('cle', models.CharField(max_length=50)),
                ('ajouter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ajouter')),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id_analyse', models.AutoField(primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='uploads/')),
                ('date', models.DateField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.AddField(
            model_name='ajouter',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
