# Generated by Django 4.1.4 on 2023-08-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cle',
        ),
        migrations.AlterField(
            model_name='analyse',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
